### ISSUE TITLE
Where is the key 5C5833E3?

### ISSUE THREAD

**Issue by jluttine** [aviau/python-pass#31]
The unit tests seem to use key id `5C5833E3`. Where is this key? I couldn't find it in the repository. Or how are the tests supposed to work?

**Comment by aviau** [comment]
I don't see any test that requires the 5C5833E3 secret key.

There are tests that use the secret key located here:
 - https://github.com/aviau/python-pass/tree/master/pypass/tests

The tests are ran in the CI, so there is nothing missing in the repo.

**Comment by jluttine** [comment]
I was referring to these lines:

- https://github.com/aviau/python-pass/blob/master/pypass/tests/test_command.py#L67
- https://github.com/aviau/python-pass/blob/master/pypass/tests/test_command.py#L78
- https://github.com/aviau/python-pass/blob/master/pypass/tests/test_command.py#L97
- https://github.com/aviau/python-pass/blob/master/pypass/tests/test_passwordstore.py#L40
- https://github.com/aviau/python-pass/blob/master/pypass/tests/test_passwordstore.py#L63
- https://github.com/aviau/python-pass/blob/master/pypass/tests/test_passwordstore.py#L168
- https://github.com/aviau/python-pass/blob/master/pypass/tests/test_passwordstore.py#L187

But indeed, looking at `.travis.yml` and `Makefile` helped me to figure out how to set up the keys for the tests. Thanks!
